### ISSUE TITLE
Kernel needed by boot.img and no known rule to make it.

### ISSUE THREAD

**Issue by galacticwarrior448** [Exynos7420/local_manifests#1]
Hey I am trying to build lineage os from this manifest for zerofltexx and [this error](https://i.imgur.com/qMqRJdN.jpg) up at 99% . Is there a way to fix this? I tried a different kernel as well and same results. I am on arch linux btw but I don't think it matters that much

**Comment by enesuzun2002** [comment]
which branch? if you have tried building lineage-17.1 branch i suggest you wait atleast till tomorrow because they have some serious bugs which i will be fixing today

**Comment by galacticwarrior448** [comment]
Ok thanks I will try again some time later.

**Comment by galacticwarrior448** [comment]
Your latest commit fixed it thanks. But now I am getting another error. I guess I should just wait .Also repo sync fails unless zeroltexx manifest file is deleted due to both of them having the same device common path.
